version: '3.2'

services:
  web:
    build:
      context: src
      dockerfile: ./Dockerfile
    command: python manage.py runserver

    depends_on:
      - db
    environment: &env
      SECRET_KEY: local
      DEBUG: 1

      DB_HOST: db
      DB_NAME: project_name
      DB_USER: project_name
      DB_PASSWORD: project_name

      CELERY_BROKER: redis://redis:6379

      ALLOWED_HOSTS: localhost

  db:
    image: postgres:13

    environment:
      POSTGRES_USER: project_name
      POSTGRES_DB: project_name
      POSTGRES_PASSWORD: project_name

  redis:
    restart: on-failure
    image: redis:6.0.10

  celery:
    restart: on-failure
    build: src
    command: celery -A src.celery worker -B -l INFO

    depends_on:
      - redis
      - db
      - web
    environment:
      <<: *env

